//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopRecipeCookBookApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        public int recipeId { get; set; }
        public string recipeTitle { get; set; }
        public string recipeDescrip { get; set; }
        public string recipeNeed { get; set; }
        public string recipeYield { get; set; }
        public string recipePrepTime { get; set; }
        public string recipeCookTime { get; set; }
        public string recipeTemp { get; set; }
        public string recipeIngred { get; set; }
        public string recipeSteps { get; set; }
        public string recipeTips { get; set; }
    }
}
